/**
 * Mock data for Phase 1 UI development.
 * Will be replaced by real API calls in Phase 6.
 */

const FOOD_IMAGES = {
  rice: 'https://images.pexels.com/photos/12669168/pexels-photo-12669168.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  meals: 'https://images.pexels.com/photos/8983398/pexels-photo-8983398.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  vegetables: 'https://images.pexels.com/photos/952485/pexels-photo-952485.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  fruits: 'https://images.pexels.com/photos/3025236/pexels-photo-3025236.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  bakery: 'https://images.pexels.com/photos/221442/pexels-photo-221442.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  packaged: 'https://images.pexels.com/photos/6995201/pexels-photo-6995201.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
};

export const HERO_IMAGE = 'https://images.pexels.com/photos/6646923/pexels-photo-6646923.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
export const LOGIN_IMAGE = 'https://images.pexels.com/photos/6591165/pexels-photo-6591165.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
export const REGISTER_IMAGE = 'https://images.pexels.com/photos/6995247/pexels-photo-6995247.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';

export const MOCK_FOOD_LISTINGS = [
  {
    id: 1,
    name: 'Cooked Rice',
    foodType: 'Rice',
    category: 'rice',
    quantity: 50,
    unit: 'kg',
    distanceKm: 2.1,
    latitude: 17.4126,
    longitude: 78.4392,
    area: 'Banjara Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    availableUntil: '8:00 PM',
    matchScore: 93,
    image: FOOD_IMAGES.rice,
    status: 'AVAILABLE',
    donor: 'Taj Banjara',
    postedAt: '2026-09-08T14:00:00Z',
  },
  {
    id: 2,
    name: 'Veg Biryani',
    foodType: 'Meals',
    category: 'meals',
    quantity: 30,
    unit: 'kg',
    distanceKm: 1.8,
    latitude: 17.4239,
    longitude: 78.4337,
    area: 'Jubilee Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    availableUntil: '9:30 PM',
    matchScore: 88,
    image: FOOD_IMAGES.meals,
    status: 'AVAILABLE',
    donor: 'Ohri\'s Restaurant',
    postedAt: '2026-09-08T13:30:00Z',
  },
  {
    id: 3,
    name: 'Fresh Vegetables',
    foodType: 'Vegetables',
    category: 'vegetables',
    quantity: 25,
    unit: 'kg',
    distanceKm: 3.5,
    latitude: 17.3849,
    longitude: 78.4135,
    area: 'Kukatpally',
    city: 'Hyderabad',
    state: 'Telangana',
    availableUntil: '6:00 PM',
    matchScore: 76,
    image: FOOD_IMAGES.vegetables,
    status: 'AVAILABLE',
    donor: 'Rythu Bazaar',
    postedAt: '2026-09-08T10:00:00Z',
  },
  {
    id: 4,
    name: 'Assorted Fruits',
    foodType: 'Fruits',
    category: 'fruits',
    quantity: 15,
    unit: 'kg',
    distanceKm: 5.8,
    latitude: 17.4474,
    longitude: 78.3713,
    area: 'Madhapur',
    city: 'Hyderabad',
    state: 'Telangana',
    availableUntil: '7:00 PM',
    matchScore: 71,
    image: FOOD_IMAGES.fruits,
    status: 'AVAILABLE',
    donor: 'Daily Fresh',
    postedAt: '2026-09-08T09:00:00Z',
  },
  {
    id: 5,
    name: 'Bread Loaves',
    foodType: 'Bakery',
    category: 'bakery',
    quantity: 40,
    unit: 'pieces',
    distanceKm: 4.2,
    latitude: 17.4374,
    longitude: 78.4487,
    area: 'Ameerpet',
    city: 'Hyderabad',
    state: 'Telangana',
    availableUntil: '5:00 PM',
    matchScore: 65,
    image: FOOD_IMAGES.bakery,
    status: 'AVAILABLE',
    donor: 'Daily Bread Bakery',
    postedAt: '2026-09-08T08:00:00Z',
  },
  {
    id: 6,
    name: 'Packaged Meals',
    foodType: 'Packaged Food',
    category: 'packaged',
    quantity: 60,
    unit: 'packets',
    distanceKm: 1.2,
    latitude: 17.4401,
    longitude: 78.3489,
    area: 'Gachibowli',
    city: 'Hyderabad',
    state: 'Telangana',
    availableUntil: '10:00 PM',
    matchScore: 95,
    image: FOOD_IMAGES.packaged,
    status: 'AVAILABLE',
    donor: 'IT Park Canteen',
    postedAt: '2026-09-08T15:00:00Z',
  },
];

export const MOCK_NGOS = [
  {
    id: 1,
    name: 'Helping Hands NGO',
    distanceKm: 1.8,
    latitude: 17.4126,
    longitude: 78.4392,
    area: 'Banjara Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    verified: true,
    capacity: '200 meals/day',
  },
  {
    id: 2,
    name: 'Food Care Foundation',
    distanceKm: 3.2,
    latitude: 17.4239,
    longitude: 78.4337,
    area: 'Jubilee Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    verified: true,
    capacity: '150 meals/day',
  },
  {
    id: 3,
    name: 'Hope Kitchen',
    distanceKm: 5.1,
    latitude: 17.3849,
    longitude: 78.4135,
    area: 'Kukatpally',
    city: 'Hyderabad',
    state: 'Telangana',
    verified: false,
    capacity: '100 meals/day',
  },
];

export const MOCK_DONATIONS = [
  {
    id: 1,
    foodName: 'Cooked Rice',
    foodType: 'Rice',
    quantity: 50,
    unit: 'kg',
    area: 'Banjara Hills',
    city: 'Hyderabad',
    status: 'MATCHED',
    ngo: 'Helping Hands NGO',
    volunteer: 'Arjun Sharma',
    image: FOOD_IMAGES.rice,
    postedAt: '2026-09-08T14:00:00Z',
  },
  {
    id: 2,
    foodName: 'Veg Biryani',
    foodType: 'Meals',
    quantity: 30,
    unit: 'kg',
    area: 'Jubilee Hills',
    city: 'Hyderabad',
    status: 'IN_TRANSIT',
    ngo: 'Food Care Foundation',
    volunteer: 'Arjun Sharma',
    image: FOOD_IMAGES.meals,
    postedAt: '2026-09-08T13:30:00Z',
  },
  {
    id: 3,
    foodName: 'Fresh Vegetables',
    foodType: 'Vegetables',
    quantity: 25,
    unit: 'kg',
    area: 'Kukatpally',
    city: 'Hyderabad',
    status: 'DELIVERED',
    ngo: 'Hope Kitchen',
    volunteer: 'Ravi Teja',
    image: FOOD_IMAGES.vegetables,
    postedAt: '2026-09-07T10:00:00Z',
  },
  {
    id: 4,
    foodName: 'Packaged Meals',
    foodType: 'Packaged Food',
    quantity: 60,
    unit: 'packets',
    area: 'Gachibowli',
    city: 'Hyderabad',
    status: 'POSTED',
    ngo: null,
    volunteer: null,
    image: FOOD_IMAGES.packaged,
    postedAt: '2026-09-08T15:00:00Z',
  },
];

export const MOCK_IMPACT = {
  mealsSaved: 12450,
  foodRescued: '3.2 tons',
  ngosConnected: 47,
  successfulDeliveries: 892,
};

// ===== Phase 2 Mock Data =====

// Coordinates for Hyderabad areas (approximate)
export const HYDERABAD_COORDS = {
  banjaraHills: { latitude: 17.4126, longitude: 78.4392 },
  jubileeHills: { latitude: 17.4239, longitude: 78.4337 },
  kukatpally: { latitude: 17.3849, longitude: 78.4135 },
  madhapur: { latitude: 17.4474, longitude: 78.3713 },
  gachibowli: { latitude: 17.4401, longitude: 78.3489 },
  ameerpet: { latitude: 17.4374, longitude: 78.4487 },
};

export const MOCK_INCOMING_DONATIONS = [
  {
    id: 101,
    foodName: 'Cooked Rice',
    foodType: 'Rice',
    quantity: 50,
    unit: 'kg',
    donor: 'Ravi Kumar',
    donorPhone: '+91 98765 43210',
    volunteer: 'Arjun Sharma',
    area: 'Banjara Hills',
    city: 'Hyderabad',
    distanceKm: 1.8,
    status: 'IN_TRANSIT',
    image: FOOD_IMAGES.rice,
    postedAt: '2026-09-08T14:00:00Z',
    etaMinutes: 18,
    pickup: { latitude: 17.4126, longitude: 78.4392, label: 'Banjara Hills' },
    destination: { latitude: 17.4239, longitude: 78.4337, label: 'Jubilee Hills' },
    matchScore: 93,
    availableUntil: '8:00 PM',
    notes: 'Hot food, please pick up before 8 PM.',
  },
  {
    id: 102,
    foodName: 'Veg Biryani',
    foodType: 'Meals',
    quantity: 30,
    unit: 'kg',
    donor: 'Ohri\'s Restaurant',
    donorPhone: '+91 98111 22334',
    volunteer: null,
    area: 'Jubilee Hills',
    city: 'Hyderabad',
    distanceKm: 0.5,
    status: 'MATCHED',
    image: FOOD_IMAGES.meals,
    postedAt: '2026-09-08T13:30:00Z',
    etaMinutes: null,
    pickup: { latitude: 17.4239, longitude: 78.4337, label: 'Jubilee Hills' },
    destination: { latitude: 17.4239, longitude: 78.4337, label: 'Jubilee Hills' },
    matchScore: 88,
    availableUntil: '9:30 PM',
    notes: '',
  },
  {
    id: 103,
    foodName: 'Fresh Vegetables',
    foodType: 'Vegetables',
    quantity: 25,
    unit: 'kg',
    donor: 'Rythu Bazaar',
    donorPhone: '+91 90000 11111',
    volunteer: 'Ravi Teja',
    area: 'Kukatpally',
    city: 'Hyderabad',
    distanceKm: 5.1,
    status: 'ASSIGNED',
    image: FOOD_IMAGES.vegetables,
    postedAt: '2026-09-08T10:00:00Z',
    etaMinutes: 25,
    pickup: { latitude: 17.3849, longitude: 78.4135, label: 'Kukatpally' },
    destination: { latitude: 17.4239, longitude: 78.4337, label: 'Jubilee Hills' },
    matchScore: 76,
    availableUntil: '6:00 PM',
    notes: 'Mixed vegetables, mostly tomatoes and leafy greens.',
  },
  {
    id: 104,
    foodName: 'Packaged Meals',
    foodType: 'Packaged Food',
    quantity: 60,
    unit: 'packets',
    donor: 'IT Park Canteen',
    donorPhone: '+91 97000 55667',
    volunteer: 'Arjun Sharma',
    area: 'Gachibowli',
    city: 'Hyderabad',
    distanceKm: 8.2,
    status: 'DELIVERED',
    image: FOOD_IMAGES.packaged,
    postedAt: '2026-09-07T15:00:00Z',
    etaMinutes: 0,
    pickup: { latitude: 17.4401, longitude: 78.3489, label: 'Gachibowli' },
    destination: { latitude: 17.4239, longitude: 78.4337, label: 'Jubilee Hills' },
    matchScore: 95,
    availableUntil: '10:00 PM',
    notes: '',
  },
];

export const MOCK_ASSIGNMENTS = [
  {
    id: 201,
    foodName: 'Cooked Rice',
    foodType: 'Rice',
    quantity: 50,
    unit: 'kg',
    donor: 'Ravi Kumar',
    donorPhone: '+91 98765 43210',
    ngo: 'Helping Hands NGO',
    ngoAddress: 'Banjara Hills, Hyderabad',
    pickupArea: 'Banjara Hills',
    pickupCity: 'Hyderabad',
    destinationArea: 'Jubilee Hills',
    destinationCity: 'Hyderabad',
    distanceKm: 4.2,
    etaMinutes: 18,
    pickupTime: '7:00 PM',
    status: 'IN_TRANSIT',
    image: FOOD_IMAGES.rice,
    assignedAt: '2026-09-08T15:00:00Z',
    pickup: { latitude: 17.4126, longitude: 78.4392, label: 'Banjara Hills' },
    destination: { latitude: 17.4239, longitude: 78.4337, label: 'Jubilee Hills' },
    notes: 'Hot food, handle carefully.',
  },
  {
    id: 202,
    foodName: 'Fresh Vegetables',
    foodType: 'Vegetables',
    quantity: 25,
    unit: 'kg',
    donor: 'Rythu Bazaar',
    donorPhone: '+91 90000 11111',
    ngo: 'Hope Kitchen',
    ngoAddress: 'Kukatpally, Hyderabad',
    pickupArea: 'Kukatpally',
    pickupCity: 'Hyderabad',
    destinationArea: 'Kukatpally',
    destinationCity: 'Hyderabad',
    distanceKm: 3.5,
    etaMinutes: 25,
    pickupTime: '5:30 PM',
    status: 'PENDING',
    image: FOOD_IMAGES.vegetables,
    assignedAt: '2026-09-08T16:00:00Z',
    pickup: { latitude: 17.3849, longitude: 78.4135, label: 'Kukatpally' },
    destination: { latitude: 17.3849, longitude: 78.4200, label: 'Kukatpally' },
    notes: '',
  },
  {
    id: 203,
    foodName: 'Packaged Meals',
    foodType: 'Packaged Food',
    quantity: 60,
    unit: 'packets',
    donor: 'IT Park Canteen',
    donorPhone: '+91 97000 55667',
    ngo: 'Food Care Foundation',
    ngoAddress: 'Jubilee Hills, Hyderabad',
    pickupArea: 'Gachibowli',
    pickupCity: 'Hyderabad',
    destinationArea: 'Jubilee Hills',
    destinationCity: 'Hyderabad',
    distanceKm: 6.8,
    etaMinutes: 0,
    pickupTime: '9:00 PM',
    status: 'DELIVERED',
    image: FOOD_IMAGES.packaged,
    assignedAt: '2026-09-07T15:00:00Z',
    pickup: { latitude: 17.4401, longitude: 78.3489, label: 'Gachibowli' },
    destination: { latitude: 17.4239, longitude: 78.4337, label: 'Jubilee Hills' },
    notes: '',
  },
  {
    id: 204,
    foodName: 'Bread Loaves',
    foodType: 'Bakery',
    quantity: 40,
    unit: 'pieces',
    donor: 'Daily Bread Bakery',
    donorPhone: '+91 98000 33445',
    ngo: 'Helping Hands NGO',
    ngoAddress: 'Banjara Hills, Hyderabad',
    pickupArea: 'Ameerpet',
    pickupCity: 'Hyderabad',
    destinationArea: 'Banjara Hills',
    destinationCity: 'Hyderabad',
    distanceKm: 2.8,
    etaMinutes: 12,
    pickupTime: '4:30 PM',
    status: 'PICKED_UP',
    image: FOOD_IMAGES.bakery,
    assignedAt: '2026-09-08T11:00:00Z',
    pickup: { latitude: 17.4374, longitude: 78.4487, label: 'Ameerpet' },
    destination: { latitude: 17.4126, longitude: 78.4392, label: 'Banjara Hills' },
    notes: '',
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 1,
    type: 'match',
    title: 'New food donation matched',
    message: 'Cooked Rice (50 kg) from Banjara Hills has been matched to your organization.',
    timestamp: '2026-09-08T15:30:00Z',
    read: false,
  },
  {
    id: 2,
    type: 'assignment',
    title: 'Volunteer assigned',
    message: 'Arjun Sharma has been assigned to deliver your incoming donation.',
    timestamp: '2026-09-08T15:45:00Z',
    read: false,
  },
  {
    id: 3,
    type: 'pickup',
    title: 'Food has been picked up',
    message: 'Arjun Sharma picked up the donation from Banjara Hills. It is now on the way.',
    timestamp: '2026-09-08T16:10:00Z',
    read: false,
  },
  {
    id: 4,
    type: 'transit',
    title: 'Donation is on the way',
    message: 'Your donation is in transit. Estimated arrival in 18 minutes.',
    timestamp: '2026-09-08T16:15:00Z',
    read: true,
  },
  {
    id: 5,
    type: 'delivered',
    title: 'Food has arrived',
    message: 'Packaged Meals (60 packets) has been delivered successfully.',
    timestamp: '2026-09-07T22:00:00Z',
    read: true,
  },
  {
    id: 6,
    type: 'new_assignment',
    title: 'New assignment available',
    message: 'A pickup from Kukatpally to Jubilee Hills is available. Distance: 5.1 km.',
    timestamp: '2026-09-08T16:00:00Z',
    read: false,
  },
];

export const MOCK_VOLUNTEER_STATS = {
  todayAssignments: 3,
  activeDelivery: 1,
  completedDeliveries: 28,
  successfulPickups: 30,
};

export const MOCK_NGO_STATS = {
  availableFood: 12,
  incomingDonations: 3,
  acceptedDonations: 8,
  activeDeliveries: 2,
  completedDeliveries: 156,
};

// ===== Phase 3 Admin Mock Data =====

export const MOCK_ADMIN_USERS = [
  { id: 1, name: 'Ravi Kumar', email: 'ravi@mealbridge.in', phone: '+91 98765 43210', role: 'DONOR', location: 'Banjara Hills, Hyderabad', createdAt: '2026-08-15T10:00:00Z' },
  { id: 2, name: 'Priya Sharma', email: 'priya@helpinghands.in', phone: '+91 98123 45678', role: 'NGO', location: 'Jubilee Hills, Hyderabad', createdAt: '2026-08-10T09:00:00Z' },
  { id: 3, name: 'Arjun Sharma', email: 'arjun@volunteer.in', phone: '+91 99887 76655', role: 'VOLUNTEER', location: 'Kukatpally, Hyderabad', createdAt: '2026-08-20T14:00:00Z' },
  { id: 4, name: 'Admin User', email: 'admin@mealbridge.in', phone: '+91 90000 00000', role: 'ADMIN', location: 'Hyderabad, Telangana', createdAt: '2026-07-01T08:00:00Z' },
  { id: 5, name: 'Sneha Reddy', email: 'sneha@mealbridge.in', phone: '+91 98765 11111', role: 'DONOR', location: 'Madhapur, Hyderabad', createdAt: '2026-08-25T11:00:00Z' },
  { id: 6, name: 'Karthik Naidu', email: 'karthik@volunteer.in', phone: '+91 97000 22222', role: 'VOLUNTEER', location: 'Gachibowli, Hyderabad', createdAt: '2026-08-28T16:00:00Z' },
  { id: 7, name: 'Lakshmi Foundation', email: 'contact@lakshmi.org', phone: '+91 96000 33333', role: 'NGO', location: 'Ameerpet, Hyderabad', createdAt: '2026-08-05T12:00:00Z' },
  { id: 8, name: 'Vikram Rao', email: 'vikram@mealbridge.in', phone: '+91 95000 44444', role: 'DONOR', location: 'Kondapur, Hyderabad', createdAt: '2026-09-01T09:30:00Z' },
  { id: 9, name: 'Anjali Gupta', email: 'anjali@volunteer.in', phone: '+91 94000 55555', role: 'VOLUNTEER', location: 'Begumpet, Hyderabad', createdAt: '2026-09-03T15:00:00Z' },
  { id: 10, name: 'Sai Teja', email: 'sai@mealbridge.in', phone: '+91 93000 66666', role: 'DONOR', location: 'Hitech City, Hyderabad', createdAt: '2026-09-05T10:00:00Z' },
];

export const MOCK_ADMIN_NGOS = [
  { id: 1, name: 'Helping Hands NGO', email: 'priya@helpinghands.in', phone: '+91 98123 45678', address: 'Road No 12, Banjara Hills', location: 'Banjara Hills, Hyderabad', capacity: '200 meals/day', foodRequirements: 'Rice, Vegetables, Cooked Meals', verified: true, verificationStatus: 'VERIFIED', createdAt: '2026-08-10T09:00:00Z' },
  { id: 2, name: 'Food Care Foundation', email: 'contact@foodcare.org', phone: '+91 97000 11111', address: 'Jubilee Hills Road No 36', location: 'Jubilee Hills, Hyderabad', capacity: '150 meals/day', foodRequirements: 'Packaged Food, Fruits', verified: true, verificationStatus: 'VERIFIED', createdAt: '2026-08-12T11:00:00Z' },
  { id: 3, name: 'Hope Kitchen', email: 'hope@kitchen.org', phone: '+91 96000 22222', address: 'KPHB Phase 1', location: 'Kukatpally, Hyderabad', capacity: '100 meals/day', foodRequirements: 'Vegetables, Rice', verified: false, verificationStatus: 'PENDING', createdAt: '2026-08-22T14:00:00Z' },
  { id: 4, name: 'Lakshmi Foundation', email: 'contact@lakshmi.org', phone: '+91 96000 33333', address: 'Ameerpet X Roads', location: 'Ameerpet, Hyderabad', capacity: '80 meals/day', foodRequirements: 'Bakery, Packaged Food', verified: false, verificationStatus: 'PENDING', createdAt: '2026-08-05T12:00:00Z' },
  { id: 5, name: 'Anna Daata Trust', email: 'annadaata@trust.org', phone: '+91 92000 77777', address: 'Secunderabad', location: 'Secunderabad, Hyderabad', capacity: '300 meals/day', foodRequirements: 'Cooked Meals, Rice, Vegetables', verified: true, verificationStatus: 'VERIFIED', createdAt: '2026-07-20T08:00:00Z' },
];

export const MOCK_ADMIN_VOLUNTEERS = [
  { id: 3, name: 'Arjun Sharma', email: 'arjun@volunteer.in', phone: '+91 99887 76655', location: 'Kukatpally, Hyderabad', availability: 'AVAILABLE', vehicleType: 'Bike', vehicleNumber: 'TS 09 AB 1234', currentLocation: 'Banjara Hills', createdAt: '2026-08-20T14:00:00Z' },
  { id: 6, name: 'Karthik Naidu', email: 'karthik@volunteer.in', phone: '+91 97000 22222', location: 'Gachibowli, Hyderabad', availability: 'AVAILABLE', vehicleType: 'Scooter', vehicleNumber: 'TS 07 CD 5678', currentLocation: 'Gachibowli', createdAt: '2026-08-28T16:00:00Z' },
  { id: 9, name: 'Anjali Gupta', email: 'anjali@volunteer.in', phone: '+91 94000 55555', location: 'Begumpet, Hyderabad', availability: 'UNAVAILABLE', vehicleType: 'Car', vehicleNumber: 'TS 08 EF 9012', currentLocation: 'Begumpet', createdAt: '2026-09-03T15:00:00Z' },
  { id: 11, name: 'Ravi Teja', email: 'ravi.teja@volunteer.in', phone: '+91 91000 88888', location: 'Madhapur, Hyderabad', availability: 'AVAILABLE', vehicleType: 'Bike', vehicleNumber: 'TS 09 GH 3456', currentLocation: 'Madhapur', createdAt: '2026-08-18T10:00:00Z' },
];

export const MOCK_ADMIN_DELIVERIES = [
  { id: 301, donationId: 1, foodName: 'Cooked Rice', donor: 'Ravi Kumar', ngo: 'Helping Hands NGO', volunteer: 'Arjun Sharma', pickupLocation: 'Banjara Hills, Hyderabad', deliveryLocation: 'Banjara Hills, Hyderabad', pickupTime: '7:00 PM', deliveryTime: null, status: 'IN_TRANSIT', assignedAt: '2026-09-08T15:00:00Z', pickup: { latitude: 17.4126, longitude: 78.4392, label: 'Banjara Hills' }, destination: { latitude: 17.4239, longitude: 78.4337, label: 'Jubilee Hills' } },
  { id: 302, donationId: 3, foodName: 'Fresh Vegetables', donor: 'Rythu Bazaar', ngo: 'Hope Kitchen', volunteer: 'Ravi Teja', pickupLocation: 'Kukatpally, Hyderabad', deliveryLocation: 'Kukatpally, Hyderabad', pickupTime: '5:30 PM', deliveryTime: '6:15 PM', status: 'DELIVERED', assignedAt: '2026-09-08T16:00:00Z', pickup: { latitude: 17.3849, longitude: 78.4135, label: 'Kukatpally' }, destination: { latitude: 17.3849, longitude: 78.4200, label: 'Kukatpally' } },
  { id: 303, donationId: 4, foodName: 'Packaged Meals', donor: 'IT Park Canteen', ngo: 'Food Care Foundation', volunteer: 'Arjun Sharma', pickupLocation: 'Gachibowli, Hyderabad', deliveryLocation: 'Jubilee Hills, Hyderabad', pickupTime: '9:00 PM', deliveryTime: '9:40 PM', status: 'DELIVERED', assignedAt: '2026-09-07T15:00:00Z', pickup: { latitude: 17.4401, longitude: 78.3489, label: 'Gachibowli' }, destination: { latitude: 17.4239, longitude: 78.4337, label: 'Jubilee Hills' } },
  { id: 304, donationId: 5, foodName: 'Bread Loaves', donor: 'Daily Bread Bakery', ngo: 'Helping Hands NGO', volunteer: 'Karthik Naidu', pickupLocation: 'Ameerpet, Hyderabad', deliveryLocation: 'Banjara Hills, Hyderabad', pickupTime: '4:30 PM', deliveryTime: null, status: 'PICKED_UP', assignedAt: '2026-09-08T11:00:00Z', pickup: { latitude: 17.4374, longitude: 78.4487, label: 'Ameerpet' }, destination: { latitude: 17.4126, longitude: 78.4392, label: 'Banjara Hills' } },
  { id: 305, donationId: 6, foodName: 'Veg Biryani', donor: 'Ohri\'s Restaurant', ngo: 'Anna Daata Trust', volunteer: null, pickupLocation: 'Jubilee Hills, Hyderabad', deliveryLocation: 'Secunderabad, Hyderabad', pickupTime: null, deliveryTime: null, status: 'ASSIGNED', assignedAt: '2026-09-08T17:00:00Z', pickup: { latitude: 17.4239, longitude: 78.4337, label: 'Jubilee Hills' }, destination: { latitude: 17.4399, longitude: 78.4987, label: 'Secunderabad' } },
];

export const MOCK_AUDIT_LOGS = [
  { id: 1001, user: 'Ravi Kumar', action: 'DONATION_CREATED', entityType: 'Donation', entityId: 1, details: 'Created donation: Cooked Rice (50 kg)', createdAt: '2026-09-08T14:00:00Z' },
  { id: 1002, user: 'System', action: 'DONATION_MATCHED', entityType: 'Match', entityId: 51, details: 'Donation #1 matched to Helping Hands NGO', createdAt: '2026-09-08T14:30:00Z' },
  { id: 1003, user: 'System', action: 'VOLUNTEER_ASSIGNED', entityType: 'Assignment', entityId: 201, details: 'Arjun Sharma assigned to delivery #301', createdAt: '2026-09-08T15:00:00Z' },
  { id: 1004, user: 'Arjun Sharma', action: 'FOOD_PICKED_UP', entityType: 'Delivery', entityId: 301, details: 'Picked up Cooked Rice from Banjara Hills', createdAt: '2026-09-08T16:10:00Z' },
  { id: 1005, user: 'Arjun Sharma', action: 'DELIVERY_STARTED', entityType: 'Delivery', entityId: 301, details: 'Delivery #301 is now in transit', createdAt: '2026-09-08T16:15:00Z' },
  { id: 1006, user: 'Ravi Teja', action: 'DELIVERY_COMPLETED', entityType: 'Delivery', entityId: 302, details: 'Delivered Fresh Vegetables to Hope Kitchen', createdAt: '2026-09-08T18:15:00Z' },
  { id: 1007, user: 'Sneha Reddy', action: 'USER_REGISTERED', entityType: 'User', entityId: 5, details: 'New donor registered: Sneha Reddy', createdAt: '2026-08-25T11:00:00Z' },
  { id: 1008, user: 'Admin User', action: 'PROFILE_UPDATED', entityType: 'User', entityId: 4, details: 'Admin profile updated', createdAt: '2026-09-01T10:00:00Z' },
  { id: 1009, user: 'System', action: 'DONATION_CREATED', entityType: 'Donation', entityId: 2, details: 'Created donation: Veg Biryani (30 kg)', createdAt: '2026-09-08T13:30:00Z' },
  { id: 1010, user: 'System', action: 'DONATION_MATCHED', entityType: 'Match', entityId: 52, details: 'Donation #2 matched to Food Care Foundation', createdAt: '2026-09-08T14:00:00Z' },
];

export const MOCK_ADMIN_STATS = {
  totalUsers: 10,
  totalDonors: 4,
  totalNgos: 5,
  totalVolunteers: 4,
  totalDonations: 48,
  activeDeliveries: 3,
  completedDeliveries: 42,
};

export const MOCK_CHART_DATA = {
  donationsOverTime: [
    { label: 'Sep 1', value: 5 },
    { label: 'Sep 2', value: 8 },
    { label: 'Sep 3', value: 6 },
    { label: 'Sep 4', value: 10 },
    { label: 'Sep 5', value: 7 },
    { label: 'Sep 6', value: 12 },
    { label: 'Sep 7', value: 9 },
    { label: 'Sep 8', value: 14 },
    { label: 'Sep 9', value: 11 },
  ],
  deliveriesOverTime: [
    { label: 'Sep 1', value: 3 },
    { label: 'Sep 2', value: 6 },
    { label: 'Sep 3', value: 4 },
    { label: 'Sep 4', value: 8 },
    { label: 'Sep 5', value: 5 },
    { label: 'Sep 6', value: 9 },
    { label: 'Sep 7', value: 7 },
    { label: 'Sep 8', value: 11 },
    { label: 'Sep 9', value: 8 },
  ],
  foodCategories: [
    { label: 'Rice', value: 12, color: '#E7B75A' },
    { label: 'Meals', value: 10, color: '#F2C76B' },
    { label: 'Vegetables', value: 8, color: '#D4A247' },
    { label: 'Fruits', value: 6, color: '#B88A38' },
    { label: 'Bakery', value: 7, color: '#9C7329' },
    { label: 'Packaged', value: 5, color: '#70706B' },
  ],
  usersByRole: [
    { label: 'Donor', value: 4, color: '#E7B75A' },
    { label: 'NGO', value: 5, color: '#F2C76B' },
    { label: 'Volunteer', value: 4, color: '#D4A247' },
    { label: 'Admin', value: 1, color: '#70706B' },
  ],
  donationStatus: [
    { label: 'Posted', value: 8, color: '#70706B' },
    { label: 'Matched', value: 6, color: '#E7B75A' },
    { label: 'Assigned', value: 5, color: '#D4A22A' },
    { label: 'Picked Up', value: 4, color: '#F2C76B' },
    { label: 'In Transit', value: 3, color: '#D4A247' },
    { label: 'Delivered', value: 22, color: '#B88A38' },
  ],
  deliveryStatus: [
    { label: 'Assigned', value: 5, color: '#D4A22A' },
    { label: 'Picked Up', value: 4, color: '#F2C76B' },
    { label: 'In Transit', value: 3, color: '#D4A247' },
    { label: 'Delivered', value: 42, color: '#B88A38' },
  ],
};
